spring.config.import=optional:file:.env[.properties]
spring.application.name=libra_auction

# DataSource Configuration
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://ep-silent-queen-a1cy03ji-pooler.ap-southeast-1.aws.neon.tech/libraauction?user=neondb_owner&password=npg_7xkfN6vozScl&sslmode=require&channelBinding=require&currentSchema=public}
spring.datasource.driverClassName=org.postgresql.Driver

# JPA/Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# Database Initialization
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:init.sql

# Liquibase Configuration
spring.liquibase.enabled=false
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml

# Server Configuration
server.port=8080
#server.servlet.context-path=/identity

# JWT Configuration
jwt.signerKey=${JWT_SIGNER_KEY:d5966b3db9693a53dcd7cabfe3e0f3b1ab63372a59747ea8d2977d9e887f3156}
jwt.valid-duration=${JWT_VALID_DURATION:3600}
jwt.refreshable-duration=${JWT_REFRESHABLE_DURATION:36000}