spring.config.import=optional:file:${user.dir}/.env[.properties],optional:configtree:./certs/

# =========================
# DATABASE
# =========================
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=create

# =========================
# Liquibase
# =========================
spring.liquibase.enabled=false

# =========================
# FILE UPLOAD LIMIT
# =========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# =========================
# JWT
# =========================
app.jwt.expiration=86400000
app.jwt.refreshable-duration=604800000

# =========================
# OAUTH2 GOOGLE
# =========================
app.google.client-id=${GOOGLE_CLIENT_ID}
app.google.client-secret=${GOOGLE_CLIENT_SECRET}
app.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# =========================
# CLOUDINARY CONFIG
# =========================
app.cloudinary.url=${CLOUDINARY_URL}

# =========================
# REDIS
# =========================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=false

# =========================
# MAIL
# =========================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true